channels:
  - conda-forge
dependencies:
  - python=3.11
  - cuda-version=12.9
  - pytorch-gpu=2.7.1
  - gymnasium=0.29.1
  - numpy>=1.26, <2.0
  - scipy=1.15.2
  - pyrealsense2
  - numba
  - imageio
  - imageio-ffmpeg
  - scikit-image
  - trimesh
  - pynput==1.7.7
  - coacd
  - rich
  - tqdm
  - joblib
  - pip
  - pip:
    - opencv-python
    - pytorch_kinematics>=0.7.5
    - dt-apriltags
