[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "furniture_bench"
version = "0.1"
description = "FurnitureBench: Reproducible Real-World Furniture Assembly Benchmark (RSS 2023)"
readme = "README.md"
requires-python = "==3.11.*"
authors = [
    {name = "CLVR @ KAIST", email = "clvr.kaist@gmail.com"}
]
urls = {Homepage = "https://github.com/clvrai/furniture-bench"}
dependencies = [
    "atomics",
    "coacd",
    "dt-apriltags",
    "gymnasium==0.29.1",
    "imageio",
    "imageio-ffmpeg",
    "joblib",
    "lxml",
    "networkx",
    "numba",
    "numpy==2.0.2",
    "opencv-python",
    "pynput==1.7.7",
    "pyrealsense2",
    "pytorch_kinematics>=0.7.5",
    "rich",
    "safetensors",
    "sapien ; platform_system == 'Linux' and platform_machine == 'x86_64'",
    "scikit-image",
    "scipy==1.15.2",
    "spnav",
    "torch==2.8.0",
    "tqdm",
    "trimesh",
]

[tool.uv]
environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
]

[tool.uv.sources]
sapien = { url = "https://github.com/yolkarian/SAPIEN/releases/download/3.0.0%2Bfork.4/sapien-3.0.0+fork.4-cp311-cp311-manylinux_2_28_x86_64.whl" }
torch = [
    { index = "pytorch-cu128" },
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.setuptools.packages.find]
where = ["."]
